externalSecret:
  - name: prod-pvs
    clusterStoreName: external-secrets-reader
    target:
      name: pvs
    data:
      - secretKey: mongo_username
        key: environment/prod-pvs
      - secretKey: mongo_password
        key: environment/prod-pvs
      - secretKey: logger_console_level
        key: environment/prod-pvs
      - secretKey: logger_ecs_format_enable
        key: environment/prod-pvs
      - secretKey: integrity_allowed_window_milis
        key: environment/prod-pvs
      - secretKey: integrity_token_expiry_min
        key: environment/prod-pvs
      - secretKey: integrity_token_delete_after_expired_min
        key: environment/prod-pvs
      - secretKey: gsa_type
        key: environment/prod-pvs
      - secretKey: gsa_project_id
        key: environment/prod-pvs
      - secretKey: gsa_private_key_id
        key: environment/prod-pvs
      - secretKey: gsa_private_key
        key: environment/prod-pvs
      - secretKey: gsa_client_email
        key: environment/prod-pvs
      - secretKey: gsa_client_id
        key: environment/prod-pvs
      - secretKey: gsa_auth_uri
        key: environment/prod-pvs
      - secretKey: gsa_token_uri
        key: environment/prod-pvs
      - secretKey: gsa_auth_provider_x509_cert_url
        key: environment/prod-pvs
      - secretKey: gsa_client_x509_cert_url
        key: environment/prod-pvs

initContainer:
  shellCommand: "go run template.go && cp production.yml /data/"
  env:
    - name: REDIS_HOST
      value: "redis-cluster"
    - name: REDIS_PORT
      value: "'6379'"
    - name: REDIS_OPTIONS_KEY_PREFIX
      value: "prod"
    - name: MONGODB_URL
      value: "mongodb://mongo01-int.geocomply.net:27017/gc_prod_pvs"
    - name: MONGODB_APPLICATION_USER
      secret: pvs/mongo_username
    - name: MONGODB_APPLICATION_PASS
      secret: pvs/mongo_password
    - name: LOGGER_CONSOLE_LEVEL
      secret: pvs/logger_console_level
    - name: LOGGER_ECS_FORMAT_ENABLE
      secret: pvs/logger_ecs_format_enable
    - name: INTEGRITY_ALLOWED_WINDOW_MILIS
      secret: pvs/integrity_allowed_window_milis
    - name: INTEGRITY_TOKEN_EXPIRY_MIN
      secret: pvs/integrity_token_expiry_min
    - name: INTEGRITY_TOKEN_DELETE_AFTER_EXPIRED_MIN
      secret: pvs/integrity_token_delete_after_expired_min
    - name: GSA_TYPE
      secret: pvs/gsa_type
    - name: GSA_PROJECT_ID
      secret: pvs/gsa_project_id
    - name: GSA_PRIVATE_KEY_ID
      secret: pvs/gsa_private_key_id
    - name: GSA_PRIVATE_KEY
      secret: pvs/gsa_private_key
    - name: GSA_CLIENT_EMAIL
      secret: pvs/gsa_client_email
    - name: GSA_CLIENT_ID
      secret: pvs/gsa_client_id
    - name: GSA_AUTH_URI
      secret: pvs/gsa_auth_uri
    - name: GSA_TOKEN_URI
      secret: pvs/gsa_token_uri
    - name: GSA_AUTH_PROVIDER_X509_CERT_URL
      secret: pvs/gsa_auth_provider_x509_cert_url
    - name: GSA_CLIENT_X509_CERT_URL
      secret: pvs/gsa_client_x509_cert_url

  image:
    name: geocomply.jfrog.io/apps-gc-pvs-docker-prod-local/init-container
    tag: v1.0.0

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 70

ingress:
  annotations: {}
  dnsServiceName: gc-pvs-prod
  tls:
    secretName: ssl-cert-dev.g7y.io

#TODO waiting for Mongo PROD
containers:
  - image:
      name: nginx
      tag: latest
      imagePullPolicy: Always

shellCommand: false

services:
  - name: gc-pvs
    port: 80
    targetPort: 80

livenessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 1
  successThreshold: 1

readinessProbe:
  httpGet:
    path: /index.html
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 3
  failureThreshold: 1
  successThreshold: 1
