{{- if .Values.TransitSecretsEngine }}
{{- $secretname := .Values.TransitSecretsEngine.name -}}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $secretname }}
  namespace: {{ $.Values.namespace }}
spec:
  data:
    {{- range .Values.TransitSecretsEngine.secrets }}
    - remoteRef:
        key: {{ .value | b64enc }}
      secretKey: {{ .name }}
    {{- end }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-transit-decrypt
  target:
    name: {{ $secretname }}
    template:
      engineVersion: v2
      data:
      {{- range .Values.TransitSecretsEngine.secrets }}
        {{ .name }}: "{{"{{"}} .{{ .name }} | b64dec {{"}}"}}"
      {{- end }}
{{- end }}