{{- if .Values.ingress.enabled -}}
{{- $fullName := include "uhre-bo.fullname" . -}}
{{- $serverPort := .Values.service.serverPort -}}
{{- if semverCompare ">=1.22-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "uhre-bo.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - secretName: {{ .Values.ingress.tls.secretName }}
      hosts:
  {{- range .Values.ingress.tls.hosts }}
        - {{ . | quote }}
  {{- end }}
{{- end }}
  rules:
  {{- if semverCompare ">=1.22-0" .Capabilities.KubeVersion.GitVersion -}}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            pathType: {{ $.Values.ingress.pathType }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: 8000
  {{- end }}
  {{- else }}
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        - path: {{ $.Values.ingress.path }}
          backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $serverPort }}
  {{- end }}
  {{- end }}
{{- end }}
