replicaCount: 1

TransitSecretsEngine:
  name: qat-uhre-1
# encrypted by https://vault-dev-tools.dev.g7y.io/ui/vault/secrets/transit/actions/kubernetes-secrets?action=encrypt
  secrets:
    - name: redispass
      value: vault:v1:SalnkBQCwJUAWY9nH2kHSl9lUsxghDK3dnoGYSEXEp7V4Ecjcw==
    - name: mysqlextpass
      value: vault:v1:nEjDHGO3R1Lyh0Gk/Ai9ugtbLfAxXVkvpT+7gLcqLeQ58sGZVjNnYe7gIw==
    - name: rabbituser
      value: vault:v1:II1qOcqqKwHTgP4oBTMokRB4ZW9aZhher2pD2oDbXa8=
    - name: rabbitpass
      value: vault:v1:jL9sTRkzyiztrCG/fZ0mUD1GnHMoYkrBiDBreNmvF0fVoXlD 
    - name: djangopass
      value: vault:v1:DvxHchcWhgMZBEcuPwAbSYwLICHkp/5zRmOAw9YZ+BocYFwH3/YZrsc=
    - name: djangouser
      value: vault:v1:JGyhnfhKBtA1dbGyDleorn5/JrWScWQnXEVFbrVD9UzTeeRWYQ==
    - name: djangomail
      value: vault:v1:yftOMQCGC2bxkujCVEWV4UluWJx2eB4CsxjfwnrE9yPvb5o1bYpEzk2swpKR+2UvYJZR
    - name: elasticuser
      value: vault:v1:K3bfD9k/cEBz9L1l8bPuObj6Q6n/tfwaSjwUrEg/zHFgdtk=
    - name: elasticpass
      value: vault:v1:K3bfD9k/cEBz9L1l8bPuObj6Q6n/tfwaSjwUrEg/zHFgdtk=
    - name: smtpuser
      value: vault:v1:x0gHWeDZIOs2HkN9u4CZK2+Aojfy/OxfhijVeRr+8u97eHkjsfkJVUY/E4kKAB117
    - name: smtppass
      value: vault:v1:AIE2vBWelU1miqDR5rN7XfL1xQGYsRceZgUDZKoHEPNf9lIBEmVjisj5ga8Kyupb2GjIoSBlECMLrV6d7R4Y/atffZHSu1rQ 
    - name: BROKER_URL
      value: vault:v1:h9SJXMVkgkRWpboVMD5ORnc3gnXJPTiwjfgCrY7a7FgLRLUp2iE3dGHjNspBMUG2nu+nrlvhlo9wZNQH0u+QUhlHxdaMwm0a/jDZdAKArhkPJuDbcupIB8uot1kH571P9maJmDHUUOuFA4DJ/cxwEaN7Ls4sBbo+zRSF2Eec0f5Ex6LCfw==
    - name: RESULT_BACKEND_URL
      value: vault:v1:ZhPYn53fuzLwXS56HO+wJv5MhmD4zfXt/3+cXDnsBBZQ8eMUubSyXew87TcuKAPv/bMeirayWbsQukJEngCoH6ahcieBoMRTN/6qzQCxonGCtYDmEvP0Heb20Z6hcpasj0et8sTWQRLgexC5eTxrYsy+N699vvYbdoKw1f4=
    - name: DB_URL
      value: vault:v1:1BcibXb4RffcvI6ROzgqKiPVnOxZjBSUIEbk4fN0MecrhUJd73Ew5YN7qLRIMwKFsPxYWF/Nbf65Jz63NHz6EA5W+RIVspU4MqmLCRMaS35fLNhsUkxfdzfWlcVL1T04ayephi8+o86FJvl9T3EExrChKStxOJEsPoI=
    - name: ELASTICSEARCH_URL
      value: vault:v1:S4ri0V8PADseJaBx0ORK9pjPLkj/GMvcfSlD/49nrNrnqetNtGwdp+2YJcnn3ZdcC1PrIhLfnuq5lPuzvI8XvvMAWwSO
    - name: REDIS_URI 
      value: vault:v1:qkx25bpDqOuia8PRNwAnPiAYH7oLi9F/purrFwjck6G5nyjHk4ThzV/PDU+VVyLS7mio6oG7CKRs9iVLq2PrIovaPKJ80zTRhvErJ6qM+FFwd5KmXnRz+Y6oL3s8j+Vs0CIyoZv4R8F6IA/Nd+hyITv2TUU=
    - name: REDBEAT_REDIS_URI
      value: vault:v1:x43yYbF7fhG/JkmIDFd8b8V6sjdtI/EhDrMS1e3Dy40cdrNxenCLqX8QVM1Mg4ln4/ECk14olZPk/Fz6CpMLvosKlRW88I9b8Ujlln0MOJMyZ/1vZr5aJGAVJiCFA7m77hH5j2xFCYh1AbfBHqbjunh7hZI=

mysql:
  enabled: false
  image:
    repository: traviixxx/uhreqat
    tag: mysql-qat1.1.0
  # imagePullSecrets: artifactory-reader
  auth:
    enabled: true
    existingSecret: qat-uhre-1
    username: rabbituser
    password: rabbitpass

redis:
  enabled: false
  architecture: standalone
  auth:
    enabled: true
    existingSecret: qat-uhre-1
    existingSecretPasswordKey: redispass

rabbitmq:
  enabled: false
  image:
    tag: 3.11.9-debian-11-r1
  auth:
    enabled: true
    existingPasswordSecret: qat-uhre-1
    username: rabbituser
    password: rabbitpass
  extraConfiguration: |-
    default_vhost = universal_hre
    default_permissions.configure = .*
    default_permissions.read = .*
    default_permissions.write = .*

image:
  repository: geocomply.jfrog.io/apps-uhre-bo-docker-dev-local/uhre-bo
  pullPolicy: Always
  tag: app-qat1.1.0

updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

service:
  type: ClusterIP
  serverPort: 8000
  targetPort: 8000
  protocol: TCP

# configMap:

#   DEBUG: "False"
#   SECRET_KEY: "replace_this_secret_key"
#   SERVER: "qat-uhre.geocomply.net"
#   DB_NAME: "universal_hre"
#   DB_USER: "rabbituser"
#   DB_PASSWORD: "rabbitpass"
#   DB_HOST: "qat-uhre-1-uhre-bo-mysql.qat-uhre-1.svc.cluster.local"
#   DB_PORT: "3306"
#   REDBEAT_REDIS_URI: "redis://:{redispass}@qat-uhre-1-uhre-bo-redis-headless.qat-uhre-1.svc.cluster.local:6379/1"
#   REDBEAT_KEY_PREFIX: "redbeat"
#   REDBEAT_DISTRIBUTOR_TASK_NAME: "interval_tasks_distributor"
#   DJANGO_SUPERUSER_USERNAME: "djangouser"
#   DJANGO_SUPERUSER_EMAIL: "djangomail"
#   DJANGO_SUPERUSER_PASSWORD: "djangopass"


ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    # haproxy-ingress.github.io/whitelist-source-range: 118.69.35.205/32,27.65.195.158/32,184.69.72.190/32,24.234.166.179/32,54.173.212.103/32,18.162.78.188/32,10.0.0.0/8
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []
  path: /
  pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
    

beatimage:
  repository: geocomply.jfrog.io/apps-uhre-bo-docker-dev-local/uhre-beat
  pullPolicy: Always
  tag: 1.1.1

cronimage:
  repository: geocomply.jfrog.io/apps-uhre-bo-docker-dev-local/uhre-cron
  pullPolicy: Always
  tag: 1.1.1

workerimage:
  repository: geocomply.jfrog.io/apps-uhre-bo-docker-dev-local/uhre-worker
  pullPolicy: Always
  tag: 1.1.1


Container:
  name: qat-uhre-1
  env:
    - name: BROKER_URL 
      secret: qat-uhre-1/BROKER_URL
    - name: RESULT_BACKEND_URL
      secret: qat-uhre-1/RESULT_BACKEND_URL
    - name: DB_URL 
      secret: qat-uhre-1/DB_URL
    - name: ELASTICSEARCH_URL
      secret: qat-uhre-1/ELASTICSEARCH_URL
    - name: REDIS_URI 
      secret: qat-uhre-1/REDIS_URI
    - name: REDBEAT_REDIS_URI 
      secret: qat-uhre-1/REDBEAT_REDIS_URI
    - name: DB_USER
      secret: qat-uhre-1/rabbituser
    - name: DB_PASSWORD
      secret: qat-uhre-1/rabbitpass
    - name: DB_NAME
      value: "universal_hre"
    - name: DB_HOST
      value: "qat-uhre-1-uhre-bo-mysql.qat-uhre-1.svc.cluster.local"
    - name: TASK_TIME_LIMIT
      value: "300"
    - name: WORKER_MAX_TASKS_PER_CHILD
      value: "100"
    - name: WORKER_MAX_MEMORY_PER_CHILD
      value: "1572864"
    - name: ELASTICSEARCH_HOST
      value: "uh-elk.geocomply.net"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ELASTICSEARCH_USER
      secret: qat-uhre-1/elasticuser
    - name: ELASTICSEARCH_PASSWORD
      secret: qat-uhre-1/elasticpass
    - name: LOGGING_FILENAME
      value: "/tmp/manager.log"
    - name: LOGGING_LEVEL
      value: "INFO"
    - name: SMTP_USER
      secret: qat-uhre-1/smtpuser
    - name: SMTP_PASSWORD
      secret: qat-uhre-1/smtppass
    - name: RABBITMQ_HOST
      value: "qat-uhre-1-uhre-bo-rabbitmq-headless.qat-uhre-1.svc.cluster.local"
    - name: RABBITMQ_PORT
      value: "5672"
    - name: RABBITMQ_DEFAULT_USER
      secret: qat-uhre-1/rabbituser
    - name: RABBITMQ_DEFAULT_PASS
      secret: qat-uhre-1/rabbituser
    - name: RABBITMQ_DEFAULT_VHOST
      value: "universal_hre"
    - name: REDIS_PASSWORD
      secret: qat-uhre-1/redispass
    - name: DEBUG
      value: "False"
    - name: SECRET_KEY
      value: "replace_this_secret_key"
    - name: REDBEAT_KEY_PREFIX
      value: "redbeat"
    - name: REDBEAT_DISTRIBUTOR_TASK_NAME   
      value: "interval_tasks_distributor"
    - name: DJANGO_SUPERUSER_USERNAME
      secret: qat-uhre-1/djangouser
    - name: DJANGO_SUPERUSER_PASSWORD
      secret: qat-uhre-1/djangopass
    - name: DJANGO_SUPERUSER_EMAIL
      secret: qat-uhre-1/djangomail



autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 4
  targetCPU: 60
  targetMemory: 60

