{{- if .Values.externalSecret }}
{{- range $k := .Values.externalSecret }}
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ $k.name }}
spec:
  refreshInterval: {{ $k.refreshInterval }}
  secretStoreRef:
    name: {{ $k.clusterStoreName | default "cluster-secretsstore" }}
    kind: ClusterSecretStore
  target:
    name: {{ $k.target.name }}
  data:
  {{- range $k.data }}
  - secretKey: {{ .secretKey }}
    remoteRef:
      key: {{ .key }}
      property: {{ .property | default .secretKey }}
  {{- end }}
{{- end }}
{{- end }}
