# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:
    inputs:
      hubAddressGroupObject:
        type: choice
        description: 'Deploy service 🚀🚀🚀'
        required: true
        default: 'demoapi'
        options:
          - 'demoapi'
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: dotnet test ./PlayStudios.MyService/
    - name: Build only
      uses: docker/build-push-action@v3
      with:
        push: false
        context: ./PlayStudios.MyService/PlayStudios.MyService.WebApi
    - name: Job result
      if: ${{ job.status == 'success' }}
      run: |
        echo "### The job has been finished successfully! :smiley:" >> $GITHUB_STEP_SUMMARY

